List countryJson = [
  /*{
    "country": "Moldova",
    "country-code": "Nd",
    "artist": "Zdob și Zdub and Frații Advahov",
    "title": "Trenulețul",
    "semi-number": 1,
    "semi-draw": 9,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Portugal",
    "country-code": "Pt",
    "artist": "Maro",
    "title": "Saudade, saudade",
    "semi-number": 1,
    "semi-draw": 10,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  }, */
  {
    "country": "Croatia",
    "country-code": "Hr",
    "artist": "Mia Dimšić",
    "title": "Guilty Pleasure",
    "semi-number": 1,
    "semi-draw": 11,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Denmark",
    "country-code": "Dk",
    "artist": "Reddi",
    "title": "The Show",
    "semi-number": 1,
    "semi-draw": 12,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Austria",
    "country-code": "At",
    "artist": "Lumix feat. Pia Maria",
    "title": "Halo",
    "semi-number": 1,
    "semi-draw": 13,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Iceland",
    "country-code": "Is",
    "artist": "Systur",
    "title": "Með hækkandi sól",
    "semi-number": 1,
    "semi-draw": 14,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Greece",
    "country-code": "Gr",
    "artist": "Amanda Georgiadi Tenfjord",
    "title": "Die Tigether",
    "semi-number": 1,
    "semi-draw": 15,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Norway",
    "country-code": "no",
    "artist": "Subwoolfer",
    "title": "Give That Wolf a Banana",
    "semi-number": 1,
    "semi-draw": 16,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Armenia",
    "country-code": "Am",
    "artist": "Rosa Linn",
    "title": "Snap",
    "semi-number": 2,
    "semi-draw": 17,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Finaldn",
    "country-code": "Fi",
    "artist": "The Rasmus",
    "title": "Jezebel",
    "semi-number": 2,
    "semi-draw": 1,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Israel",
    "country-code": "Il",
    "artist": "Michael Ben David",
    "title": "I.M",
    "semi-number": 2,
    "semi-draw": 2,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Serbia",
    "country-code": "rs",
    "artist": "Konstrakta",
    "title": "In corpore sano",
    "semi-number": 2,
    "semi-draw": 3,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Azerbiajan",
    "country-code": "Az",
    "artist": "Nadir Rustamli",
    "title": "Fade to Black",
    "semi-number": 2,
    "semi-draw": 4,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Georgia",
    "country-code": "Ge",
    "artist": "Circus Mircus",
    "title": "Fade I Am What I Am",
    "semi-number": 2,
    "semi-draw": 5,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Malta",
    "country-code": "Mt",
    "artist": "Emma Muscat",
    "title": "Fade I Am What I Am",
    "semi-number": 2,
    "semi-draw": 6,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "San Marino",
    "country-code": "Sm",
    "artist": "Achille Lauro",
    "title": "Stripper",
    "semi-number": 2,
    "semi-draw": 7,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Australia",
    "country-code": "Au",
    "artist": "Sheldon Riley",
    "title": "Not the Same",
    "semi-number": 2,
    "semi-draw": 8,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Cyprus",
    "country-code": "Cy",
    "artist": "Andromache",
    "title": "Ela",
    "semi-number": 2,
    "semi-draw": 9,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Ireland",
    "country-code": "Ie",
    "artist": "Brooke",
    "title": "That's Rich",
    "semi-number": 2,
    "semi-draw": 10,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "North Macedonia",
    "country-code": "Nk",
    "artist": "Andrea",
    "title": "Circles",
    "semi-number": 2,
    "semi-draw": 11,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Estonia",
    "country-code": "Ee",
    "artist": "Stefan",
    "title": "Hope",
    "semi-number": 2,
    "semi-draw": 12,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Romania",
    "country-code": "Ro",
    "artist": "WRS",
    "title": "Llámame",
    "semi-number": 2,
    "semi-draw": 13,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Poland",
    "country-code": "Pl",
    "artist": "Ochman",
    "title": "River",
    "semi-number": 2,
    "semi-draw": 14,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Montenegro",
    "country-code": "Me",
    "artist": "Vladana",
    "title": "Breathe",
    "semi-number": 2,
    "semi-draw": 15,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Belgium",
    "country-code": "Be",
    "artist": "Jérémie Makiese",
    "title": "Miss You",
    "semi-number": 2,
    "semi-draw": 16,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Sweden",
    "country-code": "Se",
    "artist": "Cornelia Jakobs",
    "title": "Hold Me Closer",
    "semi-number": 2,
    "semi-draw": 17,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Czech Republic",
    "country-code": "Cz",
    "artist": "We Are Domi",
    "title": "Lights Off",
    "semi-number": 2,
    "semi-draw": 18,
    "semi-place": null,
    "quailfied": null,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Italy",
    "country-code": "It",
    "artist": "Mahmood and Blanco",
    "title": "Brividi",
    "semi-number": null,
    "semi-draw": null,
    "semi-place": null,
    "quailfied": true,
    "final-draw": 9,
    "final-place": null
  },
  {
    "country": "France",
    "country-code": "Fr",
    "artist": "Alvan and Ahez",
    "title": "Fulenn",
    "semi-number": null,
    "semi-draw": null,
    "semi-place": null,
    "quailfied": true,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Germany",
    "country-code": "De",
    "artist": "Malik Harris",
    "title": "Rockstars",
    "semi-number": null,
    "semi-draw": null,
    "semi-place": null,
    "quailfied": true,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "Spain",
    "country-code": "Es",
    "artist": "Chanel",
    "title": "SloMo",
    "semi-number": null,
    "semi-draw": null,
    "semi-place": null,
    "quailfied": true,
    "final-draw": null,
    "final-place": null
  },
  {
    "country": "United Kingdom",
    "country-code": "Gb",
    "artist": "Sam Ryder",
    "title": "Space Man",
    "semi-number": null,
    "semi-draw": null,
    "semi-place": null,
    "quailfied": true,
    "final-draw": null,
    "final-place": null
  }
];
